### PR TITLE
Fix race condition for jme3 / virtual inmoov

### PR DESCRIPTION
**Pull request by moz4r**
https://github.com/MyRobotLab/myrobotlab/issues/256

### CODE REVIEW

**Comment by kwatters** [comment]
What was the actual error message?  If someone uses maryspeech will vinmoov be broken? Maybe the actual fix should be around the dependency management?

**Comment by LunDev** [comment]
@kwatters 
Copied this from the shoutbox:

> moz4r: the question is why now ... but I think we don't use audio in jme, for now, can disable it
> moz4r: progress
> moz4r: bug I think there is a fuckin conflict between marytts engine and jme3 audio engine

I couldn't get vInMoov worky either when I tried it a few days ago. But as this was my first time trying to use it, I thought something in my setup was borked and didn't look any further.
Disabling the audio for JME doesn't seem to bad (as far as I know it wasn't used anywhere?).

**Comment by kwatters** [comment]
Any idea what the underlying dependency issue was ?  It'd be nice to know if we're pulling in the wrong jar somewhere.  It's possible that one of the MarySpeech voices is pulling in a conflicting dependency somewhere.  I don't know.  If you have an error message/stack trace, especially if it shows a ClassNotFound or a NoSuchMethod exception..  That would be good to know about because there is likely a deeper issue if that's the case.

**Comment by kwatters** [comment]
@moz4r  Nice fix!  We should delete this branch now that it's merged.

**Pull request merged**
