### PR TITLE
fix jme3 crash

### PR DESCRIPTION
**Pull request by moz4r**
Oh I think this will fix random jme crash related to "State was changed after rootNode.updateGeometricState() call" .

I just removed the throw exception that break space time, replaced by a System.out.println Inside Spatial.java from jme3-core

https://github.com/MyRobotLab/myrobotlab/issues/342

### CODE REVIEW

**Comment by kwatters** [comment]
Don't replace the default JME dependency.  We don't want to maintain a custom version of this.  There needs to be a better way to fix this.  If it's a bug in JME it should be fixed and contributed to the JME project so we can pull it in as a dependency.


Do you have the full stack trace for this exception?  It's difficult to know what's going on here without seeing the full error message.   Maybe it's in a no-worky somewhere?

**Comment by kwatters** [comment]
Do you have a copy of the full stack trace/error message?  I'd like to see when this is being called from MRL.

**Comment by moz4r** [comment]
This is the only one error message I found.. before JME3 close, just after i01.startVinmoov() 
I will try to reproduce Inside eclipse for more debug, but for now occure,with the standalone jar

**Comment by kwatters** [comment]
Yeah. this sounds like a threading issue on the MRL side, not an issue with JME.

**Comment by supertick** [comment]
I have lots of jmonkey features & fixes  - I agree this is a threading issue .  Mods on the scene graph are happening before its fully initialized

**Pull request closed without merging**
